version: '3'
services:
  logwatcher:
    image: xtforgame/logwatcher:0.1
    build:
      context: https://github.com/xtforgame/log_mge_utils.git#:dist/alpine3.9/logwatcher
      dockerfile: ./Dockerfile

    container_name: logwatcher
    command: ["/usr/bin/logwatcher", "/usr/logwatcher/tmp"]

    # environment:
    #   XXXXX: "yes"

    ports:
      - "8080:8080"

    volumes:
      - "./tmp:/usr/logwatcher/tmp"
